#!/bin/bash

echo_red(){
    echo -e "\e[1;31m$1\e[0m"
}
echo_green(){
    echo -e "\e[1;32m$1\e[0m"
}
echo_yellow(){
    echo -e "\e[1;33m$1\e[0m"
}
echo_blue(){
    echo -e "\e[1;34m$1\e[0m"
}
echo_cyan(){
    echo -e "\033[0;36m$1\e[0m"
}
echo_purple(){
    echo -e "\033[1;95m$1\e[0m"
}
echo_white(){
    echo -e "\033[0;37m$1\e[0m"
}


intro() {
  echo_purple 'Hi'
  echo_purple 'Sit back and let me do all the hard parts'
  echo_purple '(-_-)'
  echo_white '--------------------------'
}

inform_human() {
  echo
  echo_purple '$msg'
}
